server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: http://localhost:9001
        predicates:
        - Path=/products/**
      - id: offer-service
        uri: http://localhost:9002
        predicates:
        - Path=/offers/**
      - id: user-service
        uri: http://localhost:9003
        predicates:
        - Path=/users/**
      - id: notification-service
        uri: http://localhost:9004
        predicates:
        - Path=/notifications/**

---

spring:
  profiles: dev
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: http://product-service:8080
        predicates:
        - Path=/products/**
      - id: offer-service
        uri: http://offer-service:8080
        predicates:
        - Path=/offers/**
      - id: user-service
        uri: http://user-service:8080
        predicates:
        - Path=/users/**
      - id: notification-service
        uri: http://notification-service:8080
        predicates:
        - Path=/notifications/**