server:
  port: 9002
message: local_value
---

spring:
  profiles: dev
  data:
    mongodb:
      host: offers-db
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/