
server:
  port: 9003
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: user-service
---

spring:
  profiles: dev
  data:
    mongodb:
      host: users-db
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/