server:
  port: 9001
spring:
  application:
    name: product-service
---

spring:
  profiles: dev
  data:
    mongodb:
      host: products-db
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/